- hosts: master-nodes
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - common
  vars:
    master: true
  #   es_config:
  #     cluster.name: "test-cluster"
  #     cluster.initial_master_nodes: "{{ inventory_hostname }}"
  #     discovery.seed_hosts: "{{ inventory_hostname }}:9300"
  #     http.host: 0.0.0.0
  #     http.port: 9200
  #     node.data: false
  #     node.master: true
  #     transport.host: 0.0.0.0
  #     transport.port: 9300
  #     bootstrap.memory_lock: false

- hosts: data-nodes
  remote_user: "{{ remote_user }}"
  become: yes
  roles:
    - common
  vars:
    master: false
  #   es_data_dirs:
  #     - "/opt/elasticsearch"
  #   es_config:
  #     cluster.name: "test-cluster"
  #     cluster.initial_master_nodes: "{{ groups['seed-nodes'] | map('extract', hostvars, inventory_hostname) }}"
  #     discovery.seed_hosts: "{{ inventory_hostname }}:9300"
  #     http.host: 0.0.0.0
  #     http.port: 9200
  #     node.data: true
  #     node.master: false
  #     transport.host: 0.0.0.0
  #     transport.port: 9300
  #     bootstrap.memory_lock: false
  #   es_plugins:
  #     - plugin: ingest-attachment
