---
# tasks file for common
- name: Import the Elasticsearch PGP Key
  shell: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -"

- name: Import the APT repository
  shell: "echo 'deb https://artifacts.elastic.co/packages/7.x/apt stable main' | sudo tee /etc/apt/sources.list.d/elastic-7.x.list"

- name: install the Elasticsearch Debian package
  apt:
    name:
      - elasticsearch
    update_cache: yes

- name: Create PID Directory
  become: yes
  file:
    path: "{{ es_pid_dir }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "755"

- name: override systemd memlock
  block:
    - name: Make sure destination dir exists
      file:
        path: "{{ sysd_config_file | dirname }}"
        state: directory
        mode: "755"

    - name: Copy specific ElasticSearch Systemd config file
      template:
        src: "override.conf.j2"
        dest: "{{ sysd_config_file }}"
        owner: root
        group: "{{ es_group }}"
        mode: "644"
        force: yes

- name: Create Others Directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: "2750"
  with_items:
    - "{{ path_repo }}"

- name: Copy Configuration File
  become: yes
  template:
    src: elasticsearch.yml.j2
    dest: "{{ es_conf_dir }}/elasticsearch.yml"
    owner: root
    group: "{{ es_group }}"
    mode: "640"
    force: yes
  notify: restart elasticsearch

- name: Copy Default File
  become: yes
  template:
    src: elasticsearch
    dest: "{{ default_file }}"
    owner: root
    group: "{{ es_group }}"
    mode: "640"
    force: yes
  notify: restart elasticsearch

- name: Copy jvm.options File
  become: yes
  template:
    src: jvm.options
    dest: "{{ es_conf_dir }}/jvm.options"
    owner: root
    group: "{{ es_group }}"
    mode: "660"
    force: yes
  notify: restart elasticsearch

- meta: flush_handlers
