---
all:
  hosts:
    # controller:
    #   ansible_connection: local
    #   ansible_ssh_host: 172.172.177.11
    node1:
      ansible_ssh_host: 52.166.60.189
      vm_private_ip: 10.0.0.10
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
      # ansible_ssh_private_key_file: /vagrant/.vagrant/machines/node1/virtualbox/private_key
    node2:
      ansible_ssh_host: 104.40.237.131
      vm_private_ip: 10.0.0.11
      ansible_ssh_private_key_file: "~/.ssh/id_rsa"
      # ansible_ssh_private_key_file: /vagrant/.vagrant/machines/node2/virtualbox/private_key
    # node3:
    #   ansible_ssh_host: 13.93.70.107
    #   ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    #   # ansible_ssh_private_key_file: /vagrant/.vagrant/machines/node3/virtualbox/private_key
  children:
    cluster-nodes:
      hosts:
        node1:
        node2:
        # node3:
    seed-nodes:
      hosts:
        node1:
